### ISSUE TITLE
Backport issues 203, 322, 536 in 1.5 branch

### ISSUE THREAD

**Issue by detonin** [uclouvain/openjpeg#611]
- [x] #203 BMP support enhancement
- [x] #322 TIFF support enhancement
- [x] #536 PNG support enhancement

**Comment by mayeut** [comment]
@detonin, fixed size integer support has been done either using the same code as was introduced in 2c3f5c269a3c34ece15de720c746d1ae809c5e4e or by using TIFF/PNG versions.
Shall something been done to define those properly in a private header ?

**Comment by detonin** [comment]
Closing, as 1.x version is not maintained anymore.
If you need this issue resolved, please switch instead to latest version where its is likely already fixed.
https://groups.google.com/d/msg/openjpeg/w2I6qPOw_KA/S85qgiy_AgAJ
